language: ruby

cache:
  directories:
  - vendor/bundle

rvm:
- 1.9.3

# Branch white list
branches:
  only:
  - amqp

notifications:
  email:
  - jack.hong@nicta.com.au

services:
- rabbitmq

before_install:
- bundle config build.nokogiri --use-system-libraries
