---
# default topic name is this machine's hostname
# this is to ensure that every RC has its own topic and AMQP account
#environment: development

communication:
  url: amqp://testbed:lab251@10.16.88.11

resources:
- type: virtual_machine
  uid: <%= Socket.gethostname %>
  image_directory: /home/vinicius/omf6-images
  img_builder: virt_install
  omf_opts:
    server: amqp://testbed:lab251@10.16.88.11
    user: testbed
    password: lab251
    topic: <%= Socket.gethostname %>
  hypervisor: xen
  hypervisor_uri: xen+ssh://vinicius@10.16.88.2/
  virt_install_path: /usr/bin/virt-install
  image_template_path: /root/images_templates
  image_path: /var/lib/libvirt/images
